### ISSUE TITLE
`position_sensor.getMotor()` crashes the controller

### ISSUE THREAD

**Issue by lukicdarkoo** [cyberbotics/webots#2540]
**Steps to Reproduce**
```Python
from controller import Robot, Node


robot = Robot()

for i in range(robot.getNumberOfDevices()):
    device = robot.getDeviceByIndex(i)
    if device.getNodeType() == Node.POSITION_SENSOR:
        motor = device.getMotor()
```

Error log:
```console
Traceback (most recent call last):
  File "/home/lukic/webots/lib/controller/python38/controller.py", line 1670, in getMotor
    return self.__motor
AttributeError: 'PositionSensor' object has no attribute '_PositionSensor__motor'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "motor.py", line 9, in <module>
    motor = device.getMotor()
  File "/home/lukic/webots/lib/controller/python38/controller.py", line 1672, in getMotor
    self.__motor = Robot.__getDeviceFromTag(self.getMotorTag())
AttributeError: type object 'Robot' has no attribute '_PositionSensor__getDeviceFromTag'
WARNING: 'motor' controller exited with status: 1.
```

**Expected behavior**
Should return a reference to the position sensor.

**System**
 - Operating System: Ubuntu 20.04
 - Graphics Card: NVIDIA GeForce GTX 1070

**Comment by lukicdarkoo** [comment]
`Robot.__getDeviceFromTag` is a private method and cannot be called outside the `Robot` class. We can rename it to `Robot.internalGetDeviceFromTag` or expose it to the Webots API
