### ISSUE TITLE
Cannot compile c/cpp with snap

### ISSUE THREAD

**Issue by BenjaminDeleze** [cyberbotics/webots#4037]
**Describe the Bug**
```
make -j 12
Traceback (most recent call last):
  File "/snap/webots/x1/usr/bin/lsb_release", line 26, in <module>
    import lsb_release
ModuleNotFoundError: No module named 'lsb_release'
# updating flying_mybot.d
Traceback (most recent call last):
  File "/snap/webots/x1/usr/bin/lsb_release", line 26, in <module>
    import lsb_release
ModuleNotFoundError: No module named 'lsb_release'
# compiling flying_mybot.c
# linking build/release/flying_mybot.o libflying_mybot.so
/snap/webots/x1/usr/bin/ld: cannot find /usr/lib/x86_64-linux-gnu/libc_nonshared.a
collect2: error: ld returned 1 exit status
make: *** [/snap/webots/x1/usr/share/webots/resources/Makefile.include:493: build/release/libflying_mybot.so] Error 1
Nothing to be done for build targets.
```

**System**
 - Operating System: ubuntu 20

**Comment by BenjaminDeleze** [comment]
Solved by reverting to core18
