### ISSUE TITLE
macOS import Error

### ISSUE THREAD

**Issue by FengJi2021** [cyberbotics/webots#4599]
`Traceback (most recent call last):
  File "/Users/tonystark/TUB_5_Semester/mpsees_rel/rl/webots/webot_world/controllers/robotSupervisorControlle/robotSupervisorControlle.py", line 1, in <module>
    from deepbots.supervisor.controllers.robot_supervisor import RobotSupervisor
  File "/usr/local/lib/python3.9/site-packages/deepbots/supervisor/controllers/robot_supervisor.py", line 2, in <module>
    from deepbots.supervisor.controllers.supervisor_env import SupervisorEnv
  File "/usr/local/lib/python3.9/site-packages/deepbots/supervisor/controllers/supervisor_env.py", line 2, in <module>
    from controller import Supervisor
  File "/Applications/Webots.app/lib/controller/python39/controller.py", line 31, in <module>
    import _controller
ImportError: dlopen(/Applications/Webots.app/lib/controller/python39/_controller.so, 0x0002): Library not loaded: /Library/Frameworks/Python.framework/Versions/3.9/Python
  Referenced from: /Applications/Webots.app/lib/controller/python39/_controller.so
  Reason: tried: '/Library/Frameworks/Python.framework/Versions/3.9/Python' (no such file), '/System/Library/Frameworks/Python.framework/Versions/3.9/Python' (no such file)
WARNING: 'robotSupervisorControlle' controller exited with status: 1.**Describe` the Bug**

**Steps to Reproduce**
1. open Webots
2. See error

**System**
 - Operating System: macOS Monterey

**Additional context**
echo $WEBOTS_HOME
/Applications/Webots.app
did not config PYTHONPATH because I did not see any use in control.py

**Comment by omichel** [comment]
Is the built-in [python example](https://github.com/cyberbotics/webots/blob/master/projects/languages/python/worlds/example.wbt) working on your machine? Which version of Webots are you using?

**Comment by BenjaminDeleze** [comment]
I'm closing this for now, feel free to reopen it if you have additional issues.
