### ISSUE TITLE
Crash when converting Panda gripper to base nodes

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#5360]
Webots crashes due to a segmenation fault when converting the Panda gripper to base nodes.

**Steps to Reproduce**
1. Go to `panda.wbt`
2. Select the `DEF GRIPPER PandaHand` node
3. Open the context menu and select "Convert to base node(s)"
4. Webots crashes

Stack trace
```
Warning: QObject::disconnect: Unexpected nullptr parameter

Thread 1 "webots-bin" received signal SIGSEGV, Segmentation fault.
0x0000555555c4c85a in WbMFNode::insertItem (this=0x5555b6f0ed90, index=0, node=0x555562975470) at vrml/WbMFNode.cpp:121
121	  assert(index >= 0 && index <= size());
(gdb) bt
#0  0x0000555555c4c85a in WbMFNode::insertItem(int, WbNode*) (this=0x5555b6f0ed90, index=0, node=0x555562975470) at vrml/WbMFNode.cpp:121
#1  0x0000555555ee48af in WbDictionary::updateDef(WbBaseNode*&, WbSFNode*, WbMFNode*, int)
    (this=0x5555b9659c70, node=@0x7fffffffa370: 0x5555b6f0f270, sfNode=0x0, mfNode=0x5555b6f0ed90, index=0) at nodes/utils/WbDictionary.cpp:152
#2  0x0000555555ee4faa in WbDictionary::updateDef(WbBaseNode*&, WbSFNode*, WbMFNode*, int)
    (this=0x5555b9659c70, node=@0x7fffffffa570: 0x5555628b6fe0, sfNode=0x0, mfNode=0x55556274f5c0, index=1) at nodes/utils/WbDictionary.cpp:239
#3  0x0000555555ee4faa in WbDictionary::updateDef(WbBaseNode*&, WbSFNode*, WbMFNode*, int)
    (this=0x5555b9659c70, node=@0x7fffffffa770: 0x555556664510, sfNode=0x5555ba7f8570, mfNode=0x0, index=-1) at nodes/utils/WbDictionary.cpp:239
#4  0x0000555555ee4da1 in WbDictionary::updateDef(WbBaseNode*&, WbSFNode*, WbMFNode*, int)
    (this=0x5555b9659c70, node=@0x7fffffffa970: 0x5555b6d74a90, sfNode=0x0, mfNode=0x5555565ae770, index=2) at nodes/utils/WbDictionary.cpp:214
#5  0x0000555555ee4faa in WbDictionary::updateDef(WbBaseNode*&, WbSFNode*, WbMFNode*, int)
    (this=0x5555b9659c70, node=@0x7fffffffab70: 0x5555565a2600, sfNode=0x0, mfNode=0x55555683a910, index=0) at nodes/utils/WbDictionary.cpp:239
#6  0x0000555555ee4faa in WbDictionary::updateDef(WbBaseNode*&, WbSFNode*, WbMFNode*, int)
    (this=0x5555b9659c70, node=@0x7fffffffad70: 0x55555659e000, sfNode=0x0, mfNode=0x55555682ee00, index=0) at nodes/utils/WbDictionary.cpp:239
#7  0x0000555555ee4faa in WbDictionary::updateDef(WbBaseNode*&, WbSFNode*, WbMFNode*, int)
    (this=0x5555b9659c70, node=@0x7fffffffaf70: 0x5555629744d0, sfNode=0x0, mfNode=0x55555cd35f50, index=46) at nodes/utils/WbDictionary.cpp:239
#8  0x0000555555ee4faa in WbDictionary::updateDef(WbBaseNode*&, WbSFNode*, WbMFNode*, int)
    (this=0x5555b9659c70, node=@0x7fffffffb030: 0x55555cc01ec0, sfNode=0x0, mfNode=0x0, index=-1) at nodes/utils/WbDictionary.cpp:239
#9  0x0000555555ee3cc8 in WbDictionary::update(bool) (this=0x5555b9659c70, load=false) at nodes/utils/WbDictionary.cpp:64
#10 0x0000555555ca399c in WbNodeOperations::updateDictionary(bool, WbBaseNode*) (this=0x5555567a89a0, load=false, protoRoot=0x5555629744d0)
    at nodes/utils/WbNodeOperations.cpp:342
#11 0x0000555555d68466 in WbSceneTree::applyNodeRegeneration(WbNode*) (this=0x555556537e10, node=0x5555629744d0) at scene_tree/WbSceneTree.cpp:1409
```

**Comment by stefaniapedrazzi** [comment]
It is not the cause of the bug, but when copying the Panda PROTO this warning is printed in the console:
```
ERROR: '/home/stefi/develop/webots/projects/robots/franka_emika/panda/worlds/panda.wbt': error: Wrong order of fields in the instance of PROTO Panda: USE nodes might refer to the wrong DEF nodes.
```

and should be fixed by listing the Robot fields in the PROTO body in the correct order.

**Comment by stefaniapedrazzi** [comment]
The issue is that the DEF and USE node are both triggering the regeneration of the same PROTO node.
This generates and infinite loop where the USE node pointer never matches the DEF node pointer because:
1. DEF node changed -> dictionary update is triggered after PROTO regeneration
2. During dictionary update, the USE node is updated to match the DEF node -> change in USE node triggers PROTO node regeneration
3. During PROTO node regeneration the parameter DEF node is recreated -> return to step 1
