### ISSUE TITLE
Error in scara_t6 example

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#5499]
The following Python controller error is displayed when running the `projects/robots/epson/scara_t6/worlds/industrial_example.wbt`
```
INFO: scara_food_industry: Starting controller: python3 -u scara_food_industry.py
INFO: conveyor_belt: Starting controller: /home/stefi/develop/webots/projects/objects/factory/conveyors/controllers/conveyor_belt/conveyor_belt 0.1 0
Traceback (most recent call last):
  File "/home/stefi/develop/webots/projects/robots/epson/scara_t6/controllers/scara_food_industry/scara_food_industry.py", line 79, in <module>
    merge_tool(fruitType, merged_tool)
  File "/home/stefi/develop/webots/projects/robots/epson/scara_t6/controllers/scara_food_industry/scara_food_industry.py", line 51, in merge_tool
    fruit.resetPhysics()
TypeError: Node.resetPhysics() missing 1 required positional argument: 'stateName'
WARNING: 'scara_food_industry' controller exited with status: 1.
```

**Comment by omichel** [comment]
This is likely due to a the new Python API. I will fix it.
