### ISSUE TITLE
Webost crash deleting nodes for which pose tracking is enabled

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#5590]
I have robot controller script that imports objects, tracks the pose of these objects, then removes them and generates a set of other object, etc.
 
 At some point during the simulation, Webots crashes with this stack
```
Thread 1 "webots-bin" received signal SIGSEGV, Segmentation fault.
0x0000555555badeb8 in WbBaseNode::isPreFinalizedCalled (this=0x0) at nodes/WbBaseNode.hpp:55
55	  bool isPreFinalizedCalled() const { return mPreFinalizeCalled; }
(gdb) y
Undefined command: "y".  Try "help".
(gdb) bt
#0  0x0000555555badeb8 in WbBaseNode::isPreFinalizedCalled() const (this=0x0) at nodes/WbBaseNode.hpp:55
#1  0x0000555555fbad1b in WbAbstractTransform::matrix() const (this=0x5555808dbf28)
    at nodes/WbAbstractTransform.cpp:353
#2  0x0000555555eee1d5 in WbSupervisorUtilities::pushRelativePoseToStream(WbDataStream&, WbTransform*, WbTransform*)
    (this=0x555560669820, stream=..., fromNode=0x0, toNode=0x5555808dbd80)
```

Webots should properly handle the deletion of nodes and suspend immediately and automatically the pose tracking.

**Comment by stefaniapedrazzi** [comment]
The same issue should also occur for tracked fields and contact points.
Given that there is no mechanism to automatically remove a field or node from the tracked list resulting in accessing deleted objects.
